movie_service:
  image:
  repository: chagraCome/movie-service
  tag: "latest"
  command: "uvicorn"
  args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
  port:  8001
  targetPort: 8000
  volumes: ./movie-service/:/app/
  envName1: DATABASE_URI
  envValue1: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
  envName2: CAST_SERVICE_HOST_URL
  envValue2: http://cast_service:8000/api/v1/casts/
  replicaCount: 1

movie_db:
  image: postgres:12.1-alpine
  tag: "latest"
  replicaCount: 1
  POSTGRES_USER: POSTGRES_USER
  OSTGRES_USER_value: movie_db_username
  POSTGRES_PASSWORD: POSTGRES_PASSWORD
  POSTGRES_PASSWORD_value: movie_db_password
  POSTGRES_DB: POSTGRES_DB
  POSTGRES_DB_value: movie_db_dev
  volumes: postgres_data_movie:/var/lib/postgresql/data/