movie_db:
  replicaCount: 1
  image: 
    repository: postgres:12.1-alpine
    tag: "latest"
  env:
    POSTGRES_USER: POSTGRES_USER
    OSTGRES_USER_value: movie_db_username
    POSTGRES_PASSWORD: POSTGRES_PASSWORD
    POSTGRES_PASSWORD_value: movie_db_password
    POSTGRES_DB: POSTGRES_DB
    POSTGRES_DB_value: movie_db_dev
  volumes: postgres_data_movie:/var/lib/postgresql/data/

movie_service:
  replicaCount: 1
  image:
    repository: chagraCome/movie-service
    tag: "latest"
    command: "uvicorn"
    args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
  service:
    port:  8001
  env:
    envName1: DATABASE_URI
    envValue1: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
    envName2: CAST_SERVICE_HOST_URL
    envValue2: http://cast_service:8000/api/v1/casts/
  volumes: ./movie-service/:/app/

cast_db:
  replicaCount: 1
  image:
    repository: postgres:12.1-alpine
    tag: "latest"
  env:
    POSTGRES_USER: POSTGRES_USER
    POSTGRES_USER_value: cast_db_username
    POSTGRES_PASSWORD: POSTGRES_PASSWORD
    POSTGRES_PASSWORD_value: cast_db_password
    POSTGRES_DB: POSTGRES_DB
    POSTGRES_DB_value: cast_db_dev
  volumes: postgres_data_cast:/var/lib/postgresql/data/

cast_service:
  replicaCount: 1
  image:
    repository: chagraCome/cast-service
    tag: "latest"
    command: "uvicorn"
    args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
  service:
    port:  8002
  env:
    envName1: DATABASE_URI
    envValue1: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
  volumes: ./cast-service/:/app/

  nginx:
    replicaCount: 1
  image:
    repository: nginx
    tag: "latest"
  service:
    port:  8000
  volumes: ./nginx_config.conf:/etc/nginx/conf.d/default.conf