{{/**** deployment****/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie_service
  labels:
    app: {{ .Release.Name }}-movie_service
spec:
  replicas: {{ .Values.movie_service.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie_service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie_service
    spec:
      containers:
        - name:     {{ .Release.Name }}-movie_service
          image: "{{ .Values.movie_service.image.repository }}:{{ .Values.movie_service.image.tag | default .Chart.AppVersion }}"
          command: [{{ .Values.movie_service.image.command }}]
          args: {{ .Values.movie_service.image.arg }}
          ports:
            - name: http
              containerPort: {{ .Values.movie_service.service.port }}
              protocol: TCP
                    env:
          env:
          - name: {{ .Values.movie_service.envName1 }}
            value: {{ .Values.movie_service.envValue1 }}
          - name: {{ .Values.movie_service.envName2 }}
            value: {{ .Values.movie_service.envValue2 }}

{{/**** deployment for movie_db ****/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie_db
  labels:
    app: {{ .Release.Name }}-movie_db
spec:
  replicas: {{ .Values.movie_db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie_db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie_db
    spec:
      containers:
        - name: {{ .Release.Name }}-movie_db
          image: "{{ .Values.movie_db.image.repository }}:{{ .Values.movie_db.image.tag | default .Chart.AppVersion }}"
          ports:
          env:
          - name: {{ .Values.movie_db.POSTGRES_USER }}
            value: {{ .Values.movie_db.OSTGRES_USER_value}}
          - name: {{ .Values.movie_db.POSTGRES_PASSWORD }}
            value: {{ .Values.movie_db.POSTGRES_PASSWORD_value }}
          - name: {{ .Values.movie_db.POSTGRES_DB }}
            value: {{ .Values.movie_db.POSTGRES_DB_value }}
      volumes: {{ .Values.movie_db.valumes }}