{{/*** service movie_db***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie_db
  labels:
    app: {{ .Release.Name }}-movie_db
spec:
  type: {{ .Values.movie_db.service.type }}
  ports:
    - port: {{ .Values.movie_db.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-movie_db

{{/**** service movie_service ****/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie_service
  labels:
    app: {{ .Release.Name }}-movie_service
spec:
  type: {{ .Values.movie_service.service.type }}
  ports:
    - port: {{ .Values.movie_service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-movie_service

{{/*** service cast_db***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast_db
  labels:
    app: {{ .Release.Name }}-cast_db
spec:
  type: {{ .Values.cast_db.service.type }}
  ports:
    - port: {{ .Values.cast_db.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cast_db
{{/*** service cast_service***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast_service
  labels:
    app: {{ .Release.Name }}-datascientest
spec:
  type: {{ .Values.cast_service.service.type }}
  ports:
    - port: {{ .Values.cast_service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cast_service

{{/***Service Nginx ***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-datascientest