apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-db
  labels:
    app: {{ .Release.Name }}-movie-db
spec:
  type: {{ .Values.movieDb.service.type }}
  ports:
    - port: {{ .Values.movieDb.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-movie-db

{{/**** service movie-service ****/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service
  labels:
    app: {{ .Release.Name }}-movie-service
spec:
  type: {{ .Values.movieService.service.type }}
  ports:
    - port: {{ .Values.movieService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-movie-service

{{/*** service cast_db***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-db
  labels:
    app: {{ .Release.Name }}-cast-db
spec:
  type: {{ .Values.castDb.service.type }}
  ports:
    - port: {{ .Values.castDb.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cast-db
{{/*** service cast_service***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-service
  labels:
    app: {{ .Release.Name }}-cast-service
spec:
  type: {{ .Values.castService.service.type }}
  ports:
    - port: {{ .Values.castService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cast-service

{{/***Service Nginx ***/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.nginx.service.type}}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cast-service